### ISSUE TITLE
Mejora de la clase Point (Feature#01)

### ISSUE THREAD

**Issue by dchiva** [dchiva/IWVG.SwC.DChiva#1]
Hola @fersousajr !

Te asigno esta tarea.

Para ver la información de la mejora puedes ir a la [wiki](https://github.com/dchiva/IWVG.SwC.DChiva/wiki/Mejora-de-la-clase-Point-%28Feature%2301%29).

Pasos importantes a seguir:
- Crea la rama Feature#01 a partir de la rama develop.
- Implementa el código necesario.
- Ejecuta los tests.
- Si todo funciona correctamente haz merge de la rama Feature#01 con develop.
- Contesta este ticket.
- Yo cerrare el ticket.

**Comment by fersousajr** [comment]
Feature#01 ok
