### ISSUE TITLE
Mejora de la clase DecimalCollection (Feature#02)

### ISSUE THREAD

**Issue by dchiva** [dchiva/IWVG.SwC.DChiva#2]
Hola @fonsi !

Te asigno esta tarea.

Para ver la información de la mejora puedes ir a la [wiki](https://github.com/dchiva/IWVG.SwC.DChiva/wiki/Mejora-de-la-clase-DecimalCollection-%28Feature%2302%29).

Pasos importantes a seguir:
- Crea la rama Feature#02 a partir de la rama develop.
- Implementa el código necesario.
- Ejecuta los tests.
- Si todo funciona correctamente haz merge de la rama Feature#02 con develop.
- Contesta este ticket.
- Yo cerrare el ticket.

**Comment by fonsi5** [comment]
Hecho,

Cualquier cosa me dices.   

Al correr los test he visto que saltan algunos errores en las validaciones de otras clases, si están asi por pruebas que estas haciendo ok, si no, échales un ojo, también sale un warning en la clase User por una libreria invocada que no usas.

Un saludo.

**Comment by dchiva** [comment]
Gracias por tu ayuda ! 

He comprobado que la mejora Feature#02 esta perfecta !!

Seguramente era porque estaba importando Calendar, pero al final era necesaria.

Un saludo, David.
