### ISSUE TITLE
Mejora de la clase User (Feature#03)

### ISSUE THREAD

**Issue by dchiva** [dchiva/IWVG.SwC.DChiva#3]
Hola @JorgeHigueraFombuena !

Te asigno esta tarea.

Para ver la información de la mejora puedes ir a la [wiki](https://github.com/dchiva/IWVG.SwC.DChiva/wiki/Mejora-de-la-clase-User-%28Feature%2303%29).

Pasos importantes a seguir:
- Crea la rama Feature#03 a partir de la rama develop.
- Implementa el código necesario.
- Ejecuta los tests.
- Si todo funciona correctamente haz merge de la rama Feature#03 con develop.
- Contesta este ticket.
- Yo cerrare el ticket.

**Comment by JorgeHigueraFombuena** [comment]
Hola
Acabo de hacerlo
Pero creo que yo debería cerrar el ticket. Eso pone en la documentación de la práctica
Compruébalo y me cuentas
Un saludo
J.

**Comment by dchiva** [comment]
Gracias por tu ayuda !

He visto que la mejora Feature#03 esta realizada a la perfección !

Si, leí tarde quién tenía que cerrar el ticket. jaja

Cierralo tú por favor.

Un saludo, David =)

**Comment by JorgeHigueraFombuena** [comment]
Hola
Lo cierro sin problemas ;)

Un salduo
J.
